//! Build-time pattern library generator.
//!
//! Reads `patterns.toml` next to this file, ensures every entry's RLE is
//! cached under `patterns_cache/<ident>.rle` (fetching from the entry's
//! LifeWiki URL if absent), parses each RLE into a width-padded plaintext
//! grid, and emits a Rust source file under `OUT_DIR` containing
//!
//!   - `pub const IDENT: Pattern = Pattern { name, rows };`  for each
//!     successfully-fetched-and-parsed entry,
//!   - `pub const ALL_<CATEGORY>: &[&Pattern]` indices, and
//!   - `pub const ALL_SEED_PATTERNS: &[&Pattern]`, the auto-reseed pool
//!     (methuselahs ∪ spaceships ∪ oscillators — guns and still-lifes
//!     intentionally excluded; see `patterns.toml`).
//!
//! Failures are non-fatal: a network error, missing curl, 404, or RLE
//! parse error logs `cargo:warning=...` and the pattern is omitted
//! from the generated constants.  The build itself only fails on
//! schema problems (malformed TOML, missing required fields, unknown
//! category) — those are author errors, not environment errors.
//!
//! Cache files are checked into the repo so offline builds and CI work
//! without network access.  The first build that introduces a new
//! pattern needs network and the system `curl` binary; subsequent
//! builds read from the cache.  We shell out to `curl` rather than
//! using a Rust HTTP crate because LifeWiki's CloudFlare layer
//! TLS-fingerprints native-Rust clients and returns 403; curl's
//! fingerprint passes.
//!
//! `cargo:rerun-if-changed` is emitted for `patterns.toml`, `build.rs`,
//! and the `patterns_cache/` directory, so editing the manifest or
//! dropping a hand-authored RLE into the cache regenerates the module.

use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

/// Per-request curl timeout (seconds).  RLEs are small (a few KB) so
/// a fast timeout fails the build quickly when the network is down
/// rather than waiting on a hung connection.
const FETCH_TIMEOUT_SECS: u32 = 30;

/// User-Agent string sent with curl fetches.  LifeWiki's CloudFlare
/// layer blocks Rust HTTP clients via TLS fingerprinting; using the
/// system `curl` binary avoids that, but we still set a UA that
/// identifies the requester rather than relying on `curl/x.y`.
const FETCH_USER_AGENT: &str =
    "Mozilla/5.0 (compatible; Anjin-Byte.github.io build-script; \
     +https://github.com/Anjin-Byte/Anjin-Byte.github.io)";

/// Categories recognised in `patterns.toml` and emitted as `ALL_<CAT>`
/// indices.  Order here is the order categories appear in the generated
/// file — purely cosmetic.
const VALID_CATEGORIES: &[&str] =
    &["methuselah", "spaceship", "oscillator", "gun", "still_life"];

/// Categories that contribute to the auto-reseed pool.  Guns emit
/// spaceships forever and would compound alive-count too aggressively;
/// still-lifes never decay and would accumulate as immortal clutter.
const SEED_POOL_CATEGORIES: &[&str] = &["methuselah", "spaceship", "oscillator"];

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let toml_path = manifest_dir.join("patterns.toml");
    let cache_dir = manifest_dir.join("patterns_cache");
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let out_path = out_dir.join("patterns_generated.rs");

    println!("cargo:rerun-if-changed=patterns.toml");
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=patterns_cache");

    fs::create_dir_all(&cache_dir).expect("create patterns_cache directory");

    let toml_text = fs::read_to_string(&toml_path)
        .unwrap_or_else(|e| panic!("read patterns.toml: {}", e));
    let parsed: toml::Value = toml_text
        .parse()
        .unwrap_or_else(|e| panic!("parse patterns.toml: {}", e));
    let entries = parsed
        .get("patterns")
        .and_then(|v| v.as_array())
        .expect("patterns.toml: top-level [[patterns]] array missing");

    // category → idents successfully baked, in TOML order.
    let mut by_category: BTreeMap<&'static str, Vec<String>> = BTreeMap::new();
    for cat in VALID_CATEGORIES {
        by_category.insert(cat, Vec::new());
    }

    let mut out = String::new();
    out.push_str("// @generated by build.rs from patterns.toml — do not edit by hand.\n\n");

    for entry in entries {
        let ident = required_str(entry, "ident");
        let name = required_str(entry, "name");
        let category = required_str(entry, "category");
        let url = required_str(entry, "url");

        let category_static: &'static str = VALID_CATEGORIES
            .iter()
            .copied()
            .find(|c| *c == category)
            .unwrap_or_else(|| {
                panic!(
                    "pattern '{}': unknown category '{}', expected one of {:?}",
                    ident, category, VALID_CATEGORIES
                )
            });

        let cache_path = cache_dir.join(format!("{}.rle", ident));
        let rle_text = match load_or_fetch(&cache_path, url) {
            Ok(t) => t,
            Err(e) => {
                println!(
                    "cargo:warning=skipping pattern '{}' ({}): {}",
                    ident, url, e
                );
                continue;
            }
        };

        let (_w, _h, rows) = match parse_rle(&rle_text) {
            Ok(t) => t,
            Err(e) => {
                println!(
                    "cargo:warning=skipping pattern '{}': RLE parse failed: {}",
                    ident, e
                );
                continue;
            }
        };

        emit_pattern_const(&mut out, ident, name, &rows);
        by_category.get_mut(category_static).unwrap().push(ident.to_string());
    }

    for cat in VALID_CATEGORIES {
        emit_index(&mut out, category_index_name(cat), &by_category[cat]);
    }

    let mut seed_pool: Vec<&str> = Vec::new();
    for cat in SEED_POOL_CATEGORIES {
        for ident in &by_category[cat] {
            seed_pool.push(ident.as_str());
        }
    }
    let seed_pool_owned: Vec<String> = seed_pool.iter().map(|s| s.to_string()).collect();
    emit_index(&mut out, "ALL_SEED_PATTERNS", &seed_pool_owned);

    fs::write(&out_path, out).unwrap_or_else(|e| panic!("write generated module: {}", e));
}

fn required_str<'a>(entry: &'a toml::Value, field: &str) -> &'a str {
    entry
        .get(field)
        .and_then(|v| v.as_str())
        .unwrap_or_else(|| panic!("patterns.toml entry missing required field '{}'", field))
}

fn category_index_name(cat: &str) -> &'static str {
    match cat {
        "methuselah" => "ALL_METHUSELAHS",
        "spaceship" => "ALL_SPACESHIPS",
        "oscillator" => "ALL_OSCILLATORS",
        "gun" => "ALL_GUNS",
        "still_life" => "ALL_STILL_LIFES",
        other => panic!("no index name for category '{}'", other),
    }
}

fn emit_pattern_const(out: &mut String, ident: &str, name: &str, rows: &[String]) {
    out.push_str(&format!(
        "pub const {ident}: Pattern = Pattern {{\n    name: \"{name}\",\n    rows: &[\n"
    ));
    for row in rows {
        // RLE is ASCII; row chars are only 'O' and '.' — no escaping needed.
        out.push_str(&format!("        \"{row}\",\n"));
    }
    out.push_str("    ],\n};\n\n");
}

fn emit_index(out: &mut String, const_name: &str, idents: &[String]) {
    out.push_str(&format!("pub const {const_name}: &[&Pattern] = &["));
    for ident in idents {
        out.push_str(&format!("&{ident}, "));
    }
    out.push_str("];\n\n");
}

/// Read the RLE from `cache_path` if it exists; otherwise fetch from
/// `url` via the system `curl` binary, persist the body to the cache,
/// and return it.  Network or curl-availability failures bubble up as
/// `Err` so the caller can warn-and-skip.
fn load_or_fetch(cache_path: &Path, url: &str) -> Result<String, String> {
    if cache_path.exists() {
        return fs::read_to_string(cache_path).map_err(|e| e.to_string());
    }
    println!(
        "cargo:warning=fetching {} → {}",
        url,
        cache_path.display()
    );
    // -s: silent (no progress meter); -S: but still print errors;
    // -f: fail with non-zero exit on HTTP 4xx/5xx; -L: follow
    // redirects; --max-time: hard cap on the whole transfer; -A: UA.
    // Body is captured via stdout, so a partial transfer that errors
    // out can never leave a half-written file in the cache.
    let output = Command::new("curl")
        .args([
            "-sSfL",
            "--max-time",
            &FETCH_TIMEOUT_SECS.to_string(),
            "-A",
            FETCH_USER_AGENT,
            url,
        ])
        .output()
        .map_err(|e| {
            format!(
                "failed to invoke `curl` ({}); ensure curl is installed and on PATH",
                e
            )
        })?;
    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        let stderr = stderr.trim();
        return Err(format!(
            "curl exited {} ({})",
            output.status,
            if stderr.is_empty() { "no stderr" } else { stderr }
        ));
    }
    let body = String::from_utf8(output.stdout)
        .map_err(|e| format!("response was not valid UTF-8: {}", e))?;
    fs::write(cache_path, &body).map_err(|e| format!("write cache file: {}", e))?;
    Ok(body)
}

/// Parse an RLE body into (width, height, plaintext rows).  Each
/// returned row is exactly `width` chars of `'O'` (alive) or `'.'`
/// (dead).  Comments (`#…`) and the `x = …, y = …, rule = …` header
/// are honoured; we trust the header's `x` for row width and right-pad
/// short rows accordingly.
///
/// Strict on body chars — only `b`, `o`, `$`, `!`, digits, and ASCII
/// whitespace are accepted.  Multi-state RLEs (Generations rules) would
/// fail here, which is fine: the pattern library is plain Conway-rule.
fn parse_rle(text: &str) -> Result<(u32, u32, Vec<String>), String> {
    let mut width: Option<u32> = None;
    let mut height: Option<u32> = None;
    let mut body = String::new();

    for line in text.lines() {
        let trimmed = line.trim();
        if trimmed.is_empty() || trimmed.starts_with('#') {
            continue;
        }
        // Header line begins with `x` (case-insensitive on some tools but
        // LifeWiki uses lowercase).
        if width.is_none() && trimmed.starts_with('x') {
            for part in trimmed.split(',') {
                let p = part.trim();
                if let Some(rest) = p.strip_prefix('x') {
                    let val = rest.trim().trim_start_matches('=').trim();
                    width = val.parse().ok();
                } else if let Some(rest) = p.strip_prefix('y') {
                    let val = rest.trim().trim_start_matches('=').trim();
                    height = val.parse().ok();
                }
                // `rule = …` is ignored; we assume B3/S23.
            }
            continue;
        }
        body.push_str(trimmed);
    }

    let width = width.ok_or("missing 'x = …' in header")?;
    let declared_height = height.ok_or("missing 'y = …' in header")?;

    let mut grid: Vec<Vec<bool>> = Vec::new();
    let mut row: Vec<bool> = Vec::new();
    let mut run = String::new();

    let take_count = |run: &mut String| -> Result<u32, String> {
        if run.is_empty() {
            Ok(1)
        } else {
            let n = run.parse::<u32>().map_err(|e| format!("bad run-count '{}': {}", run, e))?;
            run.clear();
            Ok(n)
        }
    };

    for c in body.chars() {
        if c.is_ascii_whitespace() {
            continue;
        }
        if c.is_ascii_digit() {
            run.push(c);
            continue;
        }
        let count = match c {
            'b' | 'o' | '$' | '!' => {
                // safe — `take_count` clears `run` only on consume
                let mut local = std::mem::take(&mut run);
                let n = take_count(&mut local)?;
                run = local;
                n
            }
            other => return Err(format!("unexpected char '{}' in RLE body", other)),
        };
        match c {
            'b' => row.resize(row.len() + count as usize, false),
            'o' => row.resize(row.len() + count as usize, true),
            '$' => {
                pad_to(&mut row, width as usize);
                grid.push(std::mem::take(&mut row));
                for _ in 1..count {
                    grid.push(vec![false; width as usize]);
                }
            }
            '!' => {
                if !row.is_empty() || grid.is_empty() {
                    pad_to(&mut row, width as usize);
                    grid.push(std::mem::take(&mut row));
                }
                break;
            }
            _ => unreachable!(),
        }
    }

    // Pad to declared height — RLE bodies may end with `!` mid-row and
    // omit trailing empty rows.
    while (grid.len() as u32) < declared_height {
        grid.push(vec![false; width as usize]);
    }

    let rows: Vec<String> = grid
        .iter()
        .map(|r| r.iter().map(|&b| if b { 'O' } else { '.' }).collect::<String>())
        .collect();
    Ok((width, declared_height, rows))
}

fn pad_to(row: &mut Vec<bool>, width: usize) {
    while row.len() < width {
        row.push(false);
    }
    // Should never overflow on well-formed RLE — header `x` is the row
    // width.  If a body row exceeds `x`, leave the overflow as-is and
    // let downstream notice (shows up as a too-wide plaintext row).
}
