name: Deploy to GitHub Pages
on:
  push:
    branches: [dev]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Important to fetch the entire history

      - uses: actions/setup-node@v3
        with:
          node-version: '22.6.0'

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: '1.79.0'
          override: true

      - name: Install WASM-Pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Display Versions
        run: |
          node --version
          npm --version
          rustc --version
          wasm-pack --version
          cargo --version

      - name: Build with wasm-pack
        run: wasm-pack build --target bundler

      - name: Install NPM Dependencies
        run: |
          cd www
          npm install

      - name: Build NPM Project
        run: |
          cd www
          npm run dev

      - name: Deploy
        run: |
          git config user.name 'Anjin-Byte'
          git config user.email '77296608+Anjin-Byte@users.noreply.github.com'
          git add -f dist
          git commit -m 'Deploy to GitHub Pages'
          git push origin `git subtree split --prefix dist dev`:main --force
